### ISSUE TITLE
Bug when running main.py

### ISSUE THREAD

**Issue by BlueFalconHD** [ddorn/Asciiditor#7]
Bug:

Traceback (most recent call last):
  File "C:\Users\hjdom\Asciiditor\main.py", line 8, in <module>
    import config
  File "C:\Users\hjdom\Asciiditor\config.py", line 1, in <module>
    from helper import configlib
  File "C:\Users\hjdom\Asciiditor\helper\configlib.py", line 51, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

Platform:

Windows 10
Build: 21390.1
Windows 10 Feature Experience Pack 321.13302.10.3

**Comment by BlueFalconHD** [comment]
One fix would be to merge https://github.com/ddorn/Asciiditor/compare/master...BlueFalconHD:patch-1 with main branch. But that would only fix the issue with importing the timer.

**Comment by ddorn** [comment]
Hi @BlueFalconHD !

Thank you very much for your interest in this project. Sadly this project isn't finished and probably never will as I've moved to other projects.

However your issue isn't a problem in the code, but only that you don't have the dependency `readline` installed. It is by default on linux, but on windows you need to install https://pypi.org/project/pyreadline/ to get it.

Hope that will solve your issue. I'll mention that in the readme.
D

**Comment by ddorn** [comment]
dependencies have been made cleared in bb49ed6.
