### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by BlueFalconHD** [ddorn/Asciiditor#8]
Move timer.py and configlib.py to the base directory, as some computers have trouble finding the helper folder. Also, I can help apply you for a pypi.org package, so users do not have to install dependencies or clone a git repo. Even though this project is in early development, I have faith in it.

**Comment by ddorn** [comment]
Thanks you very much for your appreciation, it means a lot to me. I have no plans on continuing the project and so in the current state, it doesn't deserve a pypi package. However, if you are interested in continuing the development of Asciiditor, I would gladly take some time to make a few things clearer and answer any question you would have about the current code.

Regarding the folder structure, I don't understand why a computer would have troubles finding the helper folder. Did you have any error and a traceback ?

**Comment by BlueFalconHD** [comment]
Here is the error i have been getting when running `main.py`
```
PS C:\Users\hjdom\AppData\Roaming\.minecraft\saves\SKYBLOCK+ (2)\datapacks\skyblockplus>  & 'C:\Program Files\Python39\python.exe' 'c:\Users\hjdom\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\launcher' '52335' '--' 'c:\Users\hjdom\Asciiditor\main.py' 
Traceback (most recent call last):
  File "c:\Users\hjdom\Asciiditor\main.py", line 8, in <module>
    import config
  File "c:\Users\hjdom\Asciiditor\config.py", line 1, in <module>
    from helper import configlib
  File "c:\Users\hjdom\Asciiditor\helper\configlib.py", line 51, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
```

**Comment by ddorn** [comment]
Sorry for taking my time, but this is not due to the folder structure, but `readline` is not installed by default on windows. To get it, run `pip install pyreadline` or any other way you use to install modules. 
It should then work as expected!
